config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('store/', include('store.urls')),
    path('warehouse/', include('warehouse.urls'))

]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [ 
    path('', views.index_page, name='index')
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [ 
    path('', views.ProductView.as_view(), name='Product'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='Product Detail'),
    path('sell/<int:pk>/', views.sell_product, name='Sell'),
    path('make_reorder/<int:pk>/', views.reorder_product, name='Reorder Product'),
]

warehouse/urls.py
from django.urls import path
from . import views

app_name = 'warehouse'

urlpatterns = [ 
    path('reorders/', views.ReorderView.as_view(), name='Reorder'),
    path('reorders/<int:pk>/', views.ReorderDetailView.as_view(), name='Reorder Detail'),
    path('process_reorder/<int:pk>/', views.process_reorder, name='Process Reorder'),
]

pages/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50)
    reorder_level = models.IntegerField(default=5)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Reorder(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    processed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.product} {self.quantity} {self.processed}"

warehouse/models.py
from django.db import models

# Create your models here.

store/forms.py
from django import forms

class SellForm(forms.Form):
    quantity = forms.IntegerField(label='Enter quantity to sell')

class ReorderForm(forms.Form):
    reorder_quantity = forms.IntegerField(label='Enter quantity to reorder')

warehouse/forms.py
from django import forms


class ProcessReorderForm(forms.Form):
    process_status = forms.BooleanField()

pages/views.py
from django.shortcuts import render

# Create your views here.
def index_page(request):
    return render(request, 'pages/index_page.html')

store/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import DetailView, ListView

from .forms import ReorderForm, SellForm
from .models import Product, Reorder


# Create your views here.
class ProductView(ListView):
    model = Product

class ProductDetailView(DetailView):
    model = Product



def sell_product(request, pk):
    product = Product.objects.get(pk=pk)
    if product.quantity <= 0:
        messages.info(request, 'Cannot sell a product with no inventory')
        return redirect('store:Product Detail', product.id)

    if request.method == 'POST':
        form = SellForm(request.POST)
        if form.is_valid():
            sell_quantity = form.cleaned_data['quantity']

            product.quantity -= int(sell_quantity)
            print(product.quantity)
            product.save()
            messages.info(request, 'Product successfully sold')
            return redirect('store:Product Detail', product.id)
    else:
        form = SellForm()
    return render(request, 'store/sell_product.html', {'form': form, 'product': product})

def reorder_product(request, pk):
    if request.method == 'POST':
        form = ReorderForm(request.POST)
        if form.is_valid():
            reorder_quantity = form.cleaned_data['reorder_quantity']
            product = Product.objects.get(pk=pk)
            reorder = Reorder.objects.create(product=product, quantity=reorder_quantity)
            messages.info(request, 'Reorder successful')
            return redirect('Reorder Detail', reorder.id)
    else:
        form = ReorderForm()
    return render(request, 'store/reorder.html', {'form': form})

warehouse/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import DetailView, ListView
from warehouse.forms import ProcessReorderForm
from store.models import Product, Reorder

# Create your views here.

class ReorderView(ListView):
    model = Reorder

class ReorderDetailView(DetailView):
    model = Reorder

def process_reorder(request, pk):
    reorder = Reorder.objects.get(pk=pk)
    product = Product.objects.get(id=reorder.product.pk)
    if request.method == 'POST':
        form = ProcessReorderForm(request.POST)
        if form.is_valid():
            process_status = form.cleaned_data['process_status']

            reorder.processed = process_status
            product_quantity_to_update = product.quantity
            reorder_quantity = reorder.quantity
            product_quantity_to_update += reorder_quantity
            product.quantity = product_quantity_to_update
            product.save()
            reorder.save()
            messages.info(request, 'Reorder processed successfully')
            return redirect('store:Product Detail', product.id)
    else:
        form = ProcessReorderForm()
    return render(request, 'warehouse/orders.html', {'form': form, 'reorder': reorder, 'product': product})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Reorder Module</title>
</head>
<body>
    <header>
        <h1>Simple Reorder Module</h1>
    </header>
    <div>
    {% block content %}
    {% endblock content %}
    </div>
</body>
</html>

templates/pages/index_page.html
{% extends "base.html"%}

{% block content %}
<a href="{% url 'store:Product' %}" target="_blank">Store</a>
<br>
<a href="{% url 'warehouse:Reorder' %}" target="_blank">Warehouse</a>
{% endblock %}

templates/store/product_detail.html
{% extends "base.html" %}


{% block content %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <h1>Product Detail</h1>
        <div>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Quantity</th>
                    <th>Reorder Level</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>{{ product.reorder_level }}</td>
                </tr>
            </tbody>
        </table>
        <br>
        <a href="{% url 'store:Sell' product.pk %}">
            <button type="submit">SELL</button>
        </a>
        <a href="{% url 'store:Reorder Product' product.pk %}">
            <button type="submit">REORDER</button>
        </a>
        

        <br>
        <a href="{% url 'store:Product' %}">Back to Product List</a>
        <br>

{% endblock %}

templates/store/product_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Product List</h1>
        <div>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Quantity</th>
                    <th>Reorder Level</th>
                </tr>
            </thead>
            <tbody>
                {% for product in object_list  %}
                    <tr>
                    <td><a href="{{ product.pk }}">{{ product.name }}</a> </td>
                    <td> {{ product.quantity }} </td>
                    <td> {{ product.reorder_level }} </td>     
                {% endfor %}
                    </tr>
            </tbody>
        </table>
        <br>
        <a href="{% url 'warehouse:Reorder' %}">Click here to view product reorders</a>
{% endblock %}

templates/store/reorder.html
{% extends "base.html" %}

{% block content%}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="SUBMIT">
</form>
{% endblock %}

templates/store/reorder_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Reorder List</h1>
        <div>
        <table>
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Reorder Quantity</th>
                    <th>Status</th>
                    <th>Process Reorder</th>
                </tr>
            </thead>
            <tbody>
                {% for reorder in object_list  %}
                    <tr>
                    <td><a href="{{ reorder.pk }}">{{ reorder.product }}</a> </td>
                    <td> {{ reorder.quantity }} </td>
                    <td> {{ reorder.processed }} </td>
                    {% if reorder.status == True %}
                    <td><span>Processed</span></td>
                    {% else %}
                    <td>
                        <a href="{% url 'warehouse:Process Reorder' reorder.pk%}">
                            <button type="submit">
                                Process Reorder
                            </button>
                        </a>
                    </td>   
                    {% endif %}
                {% endfor %}
                    </tr>
            </tbody>
        </table>
        <br>
{% endblock %}

templates/store/sell_product.html
{% extends "base.html"%}

{% block content %}
<p>This is a sale for {{ product.name }} that has a current quantity of {{ product.quantity}}</p>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="SUBMIT">
</form>
{% endblock %}

templates/warehouse/orders.html
{% extends "base.html" %}

{% block content%}
<p>This is the reorder for {{ product.name }} that has a current quantity of {{ product.quantity}}</p>
<p>Reorder quantity to be processed: {{ reorder.quantity }}</p>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="SUBMIT">
</form>
{% endblock %}

templates/warehouse/process_reorder.html
{% extends "base.html" %}

{% block content %}
    <h1>Reorder Detail</h1>
        <div>
        <table>
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Reorder Quantity</th>
                    <th>Processed Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ reorder.product }}</td>
                    <td>{{ reorder.quantity }}</td>
                    <td>{{ reorder.processed }}</td>
                </tr>
            </tbody>
        </table>
        <br>
        <a href="{% url 'warehouse:Process Reorder' reorder.pk %}">
            <button type="submit">DISPATCH</button>
        </a>

        <br>
        <a href="{% url 'store:Product' %}">Back to Product List</a>
        <br>
        <a href="{% url 'warehouse:Reorder' %}">Back to Reorder List</a>
{% endblock %}